class Node: ...

class Program(Node):
    def __init__(self, classes): self.classes = classes

class Class(Node):
    def __init__(self, name, parent, features): ...

class Feature(Node): ...

class Method(Feature):
    def __init__(self, name, formals, return_type, body): ...

class Attribute(Feature):
    def __init__(self, name, type_, init): ...

class Expr(Node): ...

class Assign(Expr): ...
class Dispatch(Expr): ...
class If(Expr): ...
class While(Expr): ...
class Block(Expr): ...
class Let(Expr): ...
class Case(Expr): ...
class New(Expr): ...
class IsVoid(Expr): ...
class BinaryOp(Expr): ...
class UnaryOp(Expr): ...
class Id(Expr): ...
class IntLit(Expr): ...
class StringLit(Expr): ...
class BoolLit(Expr): ...